import SwiftUI

// Generated by Supernova - do not modify manually
extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // Pink
        
        // 10
        let pink10 = Color(.sRGB, red: 254/255, green: 240/255, blue: 245/255, opacity: 1) 
        
        // 20
        let pink20 = Color(.sRGB, red: 253/255, green: 213/255, blue: 228/255, opacity: 1) 
        
        // 30
        let pink30 = Color(.sRGB, red: 251/255, green: 178/255, blue: 207/255, opacity: 1) 
        
        // 40
        let pink40 = Color(.sRGB, red: 249/255, green: 129/255, blue: 183/255, opacity: 1) 
        
        // 50
        let pink50 = Color(.sRGB, red: 244/255, green: 76/255, blue: 162/255, opacity: 1) 
        
        // 60
        let pink60 = Color(.sRGB, red: 204/255, green: 40/255, blue: 130/255, opacity: 1) 
        
        // 70
        let pink70 = Color(.sRGB, red: 154/255, green: 27/255, blue: 96/255, opacity: 1) 
        
        // 80
        let pink80 = Color(.sRGB, red: 115/255, green: 0/255, blue: 69/255, opacity: 1) 
        
        // 90
        let pink90 = Color(.sRGB, red: 80/255, green: 0/255, blue: 46/255, opacity: 1) 
        
        // 95
        let pink95 = Color(.sRGB, red: 67/255, green: 0/255, blue: 38/255, opacity: 1) 
        
        // 100
        let pink100 = Color(.sRGB, red: 51/255, green: 0/255, blue: 27/255, opacity: 1) 
        
        // 5
        let pink5 = Color(.sRGB, red: 255/255, green: 248/255, blue: 250/255, opacity: 1) 

        // Purple
        
        // 5
        let purple5 = Color(.sRGB, red: 250/255, green: 249/255, blue: 254/255, opacity: 1) 
        
        // 10
        let purple10 = Color(.sRGB, red: 245/255, green: 242/255, blue: 253/255, opacity: 1) 
        
        // 20
        let purple20 = Color(.sRGB, red: 227/255, green: 219/255, blue: 250/255, opacity: 1) 
        
        // 30
        let purple30 = Color(.sRGB, red: 206/255, green: 190/255, blue: 247/255, opacity: 1) 
        
        // 40
        let purple40 = Color(.sRGB, red: 180/255, green: 154/255, blue: 242/255, opacity: 1) 
        
        // 50
        let purple50 = Color(.sRGB, red: 159/255, green: 120/255, blue: 237/255, opacity: 1) 
        
        // 60
        let purple60 = Color(.sRGB, red: 135/255, green: 76/255, blue: 230/255, opacity: 1) 
        
        // 70
        let purple70 = Color(.sRGB, red: 106/255, green: 43/255, blue: 191/255, opacity: 1) 
        
        // 80
        let purple80 = Color(.sRGB, red: 74/255, green: 28/255, blue: 137/255, opacity: 1) 
        
        // 90
        let purple90 = Color(.sRGB, red: 50/255, green: 16/255, blue: 96/255, opacity: 1) 
        
        // 95
        let purple95 = Color(.sRGB, red: 41/255, green: 12/255, blue: 81/255, opacity: 1) 
        
        // 100
        let purple100 = Color(.sRGB, red: 30/255, green: 7/255, blue: 62/255, opacity: 1) 

        // Teal
        
        // 5
        let teal5 = Color(.sRGB, red: 231/255, green: 254/255, blue: 254/255, opacity: 1) 
        
        // 10
        let teal10 = Color(.sRGB, red: 205/255, green: 253/255, blue: 253/255, opacity: 1) 
        
        // 20
        let teal20 = Color(.sRGB, red: 131/255, green: 241/255, blue: 241/255, opacity: 1) 
        
        // 30
        let teal30 = Color(.sRGB, red: 61/255, green: 219/255, blue: 219/255, opacity: 1) 
        
        // 40
        let teal40 = Color(.sRGB, red: 0/255, green: 187/255, blue: 187/255, opacity: 1) 
        
        // 50
        let teal50 = Color(.sRGB, red: 0/255, green: 158/255, blue: 158/255, opacity: 1) 
        
        // 60
        let teal60 = Color(.sRGB, red: 30/255, green: 124/255, blue: 123/255, opacity: 1) 
        
        // 70
        let teal70 = Color(.sRGB, red: 0/255, green: 92/255, blue: 92/255, opacity: 1) 
        
        // 80
        let teal80 = Color(.sRGB, red: 0/255, green: 65/255, blue: 64/255, opacity: 1) 
        
        // 90
        let teal90 = Color(.sRGB, red: 0/255, green: 43/255, blue: 43/255, opacity: 1) 
        
        // 95
        let teal95 = Color(.sRGB, red: 0/255, green: 34/255, blue: 34/255, opacity: 1) 
        
        // 100
        let teal100 = Color(.sRGB, red: 0/255, green: 25/255, blue: 25/255, opacity: 1) 

        // Yellow
        
        // 5
        let yellow5 = Color(.sRGB, red: 253/255, green: 249/255, blue: 235/255, opacity: 1) 
        
        // 10
        let yellow10 = Color(.sRGB, red: 252/255, green: 244/255, blue: 214/255, opacity: 1) 
        
        // 20
        let yellow20 = Color(.sRGB, red: 250/255, green: 221/255, blue: 153/255, opacity: 1) 
        
        // 30
        let yellow30 = Color(.sRGB, red: 241/255, green: 194/255, blue: 27/255, opacity: 1) 
        
        // 40
        let yellow40 = Color(.sRGB, red: 210/255, green: 161/255, blue: 6/255, opacity: 1) 
        
        // 50
        let yellow50 = Color(.sRGB, red: 178/255, green: 134/255, blue: 0/255, opacity: 1) 
        
        // 60
        let yellow60 = Color(.sRGB, red: 142/255, green: 106/255, blue: 0/255, opacity: 1) 
        
        // 70
        let yellow70 = Color(.sRGB, red: 104/255, green: 78/255, blue: 0/255, opacity: 1) 
        
        // 80
        let yellow80 = Color(.sRGB, red: 72/255, green: 55/255, blue: 0/255, opacity: 1) 
        
        // 90
        let yellow90 = Color(.sRGB, red: 48/255, green: 36/255, blue: 0/255, opacity: 1) 
        
        // 95
        let yellow95 = Color(.sRGB, red: 38/255, green: 28/255, blue: 0/255, opacity: 1) 
        
        // 100
        let yellow100 = Color(.sRGB, red: 28/255, green: 21/255, blue: 0/255, opacity: 1) 

        // Orange
        
        // 5
        let orange5 = Color(.sRGB, red: 255/255, green: 248/255, blue: 243/255, opacity: 1) 
        
        // 10
        let orange10 = Color(.sRGB, red: 255/255, green: 242/255, blue: 232/255, opacity: 1) 
        
        // 20
        let orange20 = Color(.sRGB, red: 255/255, green: 217/255, blue: 190/255, opacity: 1) 
        
        // 30
        let orange30 = Color(.sRGB, red: 255/255, green: 183/255, blue: 132/255, opacity: 1) 
        
        // 40
        let orange40 = Color(.sRGB, red: 255/255, green: 131/255, blue: 43/255, opacity: 1) 
        
        // 50
        let orange50 = Color(.sRGB, red: 227/255, green: 107/255, blue: 0/255, opacity: 1) 
        
        // 60
        let orange60 = Color(.sRGB, red: 186/255, green: 78/255, blue: 0/255, opacity: 1) 
        
        // 70
        let orange70 = Color(.sRGB, red: 138/255, green: 56/255, blue: 0/255, opacity: 1) 
        
        // 80
        let orange80 = Color(.sRGB, red: 94/255, green: 41/255, blue: 0/255, opacity: 1) 
        
        // 90
        let orange90 = Color(.sRGB, red: 62/255, green: 26/255, blue: 0/255, opacity: 1) 
        
        // 95
        let orange95 = Color(.sRGB, red: 51/255, green: 20/255, blue: 0/255, opacity: 1) 
        
        // 100
        let orange100 = Color(.sRGB, red: 35/255, green: 16/255, blue: 0/255, opacity: 1) 

        // Red
        
        // 5
        let red5 = Color(.sRGB, red: 255/255, green: 248/255, blue: 248/255, opacity: 1) 
        
        // 10
        let red10 = Color(.sRGB, red: 255/255, green: 240/255, blue: 240/255, opacity: 1) 
        
        // 20
        let red20 = Color(.sRGB, red: 255/255, green: 214/255, blue: 214/255, opacity: 1) 
        
        // 30
        let red30 = Color(.sRGB, red: 255/255, green: 179/255, blue: 179/255, opacity: 1) 
        
        // 40
        let red40 = Color(.sRGB, red: 255/255, green: 132/255, blue: 132/255, opacity: 1) 
        
        // 50
        let red50 = Color(.sRGB, red: 247/255, green: 85/255, blue: 86/255, opacity: 1) 
        
        // 60
        let red60 = Color(.sRGB, red: 210/255, green: 48/255, blue: 49/255, opacity: 1) 
        
        // 70
        let red70 = Color(.sRGB, red: 158/255, green: 33/255, blue: 34/255, opacity: 1) 
        
        // 80
        let red80 = Color(.sRGB, red: 113/255, green: 21/255, blue: 22/255, opacity: 1) 
        
        // 90
        let red90 = Color(.sRGB, red: 78/255, green: 11/255, blue: 12/255, opacity: 1) 
        
        // 95
        let red95 = Color(.sRGB, red: 64/255, green: 7/255, blue: 8/255, opacity: 1) 
        
        // 100
        let red100 = Color(.sRGB, red: 49/255, green: 5/255, blue: 5/255, opacity: 1) 

        // Green
        
        // 5
        let green5 = Color(.sRGB, red: 234/255, green: 254/255, blue: 239/255, opacity: 1) 
        
        // 10
        let green10 = Color(.sRGB, red: 211/255, green: 254/255, blue: 222/255, opacity: 1) 
        
        // 20
        let green20 = Color(.sRGB, red: 164/255, green: 241/255, blue: 187/255, opacity: 1) 
        
        // 30
        let green30 = Color(.sRGB, red: 127/255, green: 218/255, blue: 155/255, opacity: 1) 
        
        // 40
        let green40 = Color(.sRGB, red: 76/255, green: 190/255, blue: 117/255, opacity: 1) 
        
        // 50
        let green50 = Color(.sRGB, red: 0/255, green: 164/255, blue: 84/255, opacity: 1) 
        
        // 60
        let green60 = Color(.sRGB, red: 0/255, green: 129/255, blue: 65/255, opacity: 1) 
        
        // 70
        let green70 = Color(.sRGB, red: 0/255, green: 96/255, blue: 47/255, opacity: 1) 
        
        // 80
        let green80 = Color(.sRGB, red: 0/255, green: 67/255, blue: 31/255, opacity: 1) 
        
        // 90
        let green90 = Color(.sRGB, red: 0/255, green: 45/255, blue: 18/255, opacity: 1) 
        
        // 95
        let green95 = Color(.sRGB, red: 0/255, green: 37/255, blue: 13/255, opacity: 1) 
        
        // 100
        let green100 = Color(.sRGB, red: 0/255, green: 26/255, blue: 8/255, opacity: 1) 

        // Blue
        
        // 5
        let blue5 = Color(.sRGB, red: 246/255, green: 250/255, blue: 255/255, opacity: 1) 
        
        // 10
        let blue10 = Color(.sRGB, red: 237/255, green: 245/255, blue: 255/255, opacity: 1) 
        
        // 20
        let blue20 = Color(.sRGB, red: 208/255, green: 226/255, blue: 255/255, opacity: 1) 
        
        // 30
        let blue30 = Color(.sRGB, red: 166/255, green: 200/255, blue: 255/255, opacity: 1) 
        
        // 40
        let blue40 = Color(.sRGB, red: 120/255, green: 169/255, blue: 255/255, opacity: 1) 
        
        // 50
        let blue50 = Color(.sRGB, red: 69/255, green: 137/255, blue: 255/255, opacity: 1) 
        
        // 60
        let blue60 = Color(.sRGB, red: 15/255, green: 98/255, blue: 254/255, opacity: 1) 
        
        // 70
        let blue70 = Color(.sRGB, red: 0/255, green: 67/255, blue: 206/255, opacity: 1) 
        
        // 80
        let blue80 = Color(.sRGB, red: 0/255, green: 45/255, blue: 156/255, opacity: 1) 
        
        // 90
        let blue90 = Color(.sRGB, red: 0/255, green: 29/255, blue: 108/255, opacity: 1) 
        
        // 95
        let blue95 = Color(.sRGB, red: 0/255, green: 23/255, blue: 90/255, opacity: 1) 
        
        // 100
        let blue100 = Color(.sRGB, red: 0/255, green: 17/255, blue: 65/255, opacity: 1) 

        // Grey
        
        // 5
        let grey5 = Color(.sRGB, red: 249/255, green: 249/255, blue: 250/255, opacity: 1) 
        
        // 10
        let grey10 = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        
        // 20
        let grey20 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        
        // 30
        let grey30 = Color(.sRGB, red: 192/255, green: 199/255, blue: 206/255, opacity: 1) 
        
        // 40
        let grey40 = Color(.sRGB, red: 159/255, green: 170/255, blue: 180/255, opacity: 1) 
        
        // 50
        let grey50 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        
        // 60
        let grey60 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 
        
        // 70
        let grey70 = Color(.sRGB, red: 78/255, green: 83/255, blue: 88/255, opacity: 1) 
        
        // 80
        let grey80 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 
        
        // 90
        let grey90 = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        
        // 95
        let grey95 = Color(.sRGB, red: 25/255, green: 28/255, blue: 30/255, opacity: 1) 
        
        // 100
        let grey100 = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 

        // White
        
        // 0
        let white0 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // Base

        // Autocomplete
        
        // Snippet Light
        let autocompleteSnippetLight = Color(.sRGB, red: 254/255, green: 240/255, blue: 245/255, opacity: 1) 
        
        // Snippet
        let autocompleteSnippet = Color(.sRGB, red: 244/255, green: 76/255, blue: 162/255, opacity: 1) 
        
        // Snippet Dark
        let autocompleteSnippetDark = Color(.sRGB, red: 204/255, green: 40/255, blue: 130/255, opacity: 1) 
        
        // Variable Light
        let autocompleteVariableLight = Color(.sRGB, red: 211/255, green: 254/255, blue: 222/255, opacity: 1) 
        
        // Variable
        let autocompleteVariable = Color(.sRGB, red: 0/255, green: 164/255, blue: 84/255, opacity: 1) 
        
        // Variable Dark
        let autocompleteVariableDark = Color(.sRGB, red: 0/255, green: 129/255, blue: 65/255, opacity: 1) 
        
        // Method Light
        let autocompleteMethodLight = Color(.sRGB, red: 252/255, green: 244/255, blue: 214/255, opacity: 1) 
        
        // Method
        let autocompleteMethod = Color(.sRGB, red: 178/255, green: 134/255, blue: 0/255, opacity: 1) 
        
        // Method Dark
        let autocompleteMethodDark = Color(.sRGB, red: 142/255, green: 106/255, blue: 0/255, opacity: 1) 
        
        // Transformer Light
        let autocompleteTransformerLight = Color(.sRGB, red: 237/255, green: 245/255, blue: 255/255, opacity: 1) 
        
        // Transformer
        let autocompleteTransformer = Color(.sRGB, red: 69/255, green: 137/255, blue: 255/255, opacity: 1) 
        
        // Transformer Dark
        let autocompleteTransformerDark = Color(.sRGB, red: 15/255, green: 98/255, blue: 254/255, opacity: 1) 

        // Code
        
        // Directly Exported
        let codeDirectlyExported = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 
        
        // Keywords
        let codeKeywords = Color(.sRGB, red: 69/255, green: 137/255, blue: 255/255, opacity: 1) 
        
        // Numbers
        let codeNumbers = Color(.sRGB, red: 0/255, green: 158/255, blue: 158/255, opacity: 1) 
        
        // Strings
        let codeStrings = Color(.sRGB, red: 210/255, green: 48/255, blue: 49/255, opacity: 1) 
        
        // Functions
        let codeFunctions = Color(.sRGB, red: 0/255, green: 129/255, blue: 65/255, opacity: 1) 
        
        // Methods
        let codeMethods = Color(.sRGB, red: 135/255, green: 76/255, blue: 230/255, opacity: 1) 
        
        // Control Symbols
        let codeControlSymbols = Color(.sRGB, red: 178/255, green: 134/255, blue: 0/255, opacity: 1) 
        
        // Code
        let codeCode = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 
        
        // Comment
        let codeComment = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 

        // Special
        
        // Blanket
        let specialBlanket = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 0.4) 
        
        // White Transparent Divider
        let specialWhiteTransparentDivider = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 0.24) 
        
        // White Transparent Hover
        let specialWhiteTransparentHover = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 0.12) 
        
        // Token Thumbnail Border
        let specialTokenThumbnailBorder = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 0.12) 

        // LIGHT
        
        // Background Primary Dark
        let lightBackgroundPrimaryDark = Color(.sRGB, red: 208/255, green: 226/255, blue: 255/255, opacity: 1) 
        
        // Background Success Dark
        let lightBackgroundSuccessDark = Color(.sRGB, red: 164/255, green: 241/255, blue: 187/255, opacity: 1) 
        
        // Background Critical Dark
        let lightBackgroundCriticalDark = Color(.sRGB, red: 255/255, green: 214/255, blue: 214/255, opacity: 1) 
        
        // Background Warning Dark
        let lightBackgroundWarningDark = Color(.sRGB, red: 255/255, green: 217/255, blue: 190/255, opacity: 1) 

        // Semantic
        
        // Primary Dark
        let semanticPrimaryDark = Color(.sRGB, red: 15/255, green: 98/255, blue: 254/255, opacity: 1) 
        
        // Primary Light
        let semanticPrimaryLight = Color(.sRGB, red: 120/255, green: 169/255, blue: 255/255, opacity: 1) 
        
        // Success Dark
        let semanticSuccessDark = Color(.sRGB, red: 0/255, green: 129/255, blue: 65/255, opacity: 1) 
        
        // Success Light
        let semanticSuccessLight = Color(.sRGB, red: 76/255, green: 190/255, blue: 117/255, opacity: 1) 
        
        // Critical Dark
        let semanticCriticalDark = Color(.sRGB, red: 158/255, green: 33/255, blue: 34/255, opacity: 1) 
        
        // Critical Light
        let semanticCriticalLight = Color(.sRGB, red: 247/255, green: 85/255, blue: 86/255, opacity: 1) 
        
        // Warning Dark
        let semanticWarningDark = Color(.sRGB, red: 186/255, green: 78/255, blue: 0/255, opacity: 1) 
        
        // Warning Light
        let semanticWarningLight = Color(.sRGB, red: 255/255, green: 131/255, blue: 43/255, opacity: 1) 

        // States

        // DARK
        
        // Background Black
        let darkBackgroundBlack = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 
        
        // Background 01
        let darkBackground01 = Color(.sRGB, red: 25/255, green: 28/255, blue: 30/255, opacity: 1) 
        
        // Background 02
        let darkBackground02 = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        
        // Background 03
        let darkBackground03 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 

        // LIGHT
        
        // Background White
        let lightBackgroundWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        
        // Background 01
        let lightBackground01 = Color(.sRGB, red: 249/255, green: 249/255, blue: 250/255, opacity: 1) 
        
        // Background 02
        let lightBackground02 = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        
        // Background 03
        let lightBackground03 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        
        // Background Primary
        let lightBackgroundPrimary = Color(.sRGB, red: 237/255, green: 245/255, blue: 255/255, opacity: 1) 
        
        // Background Success
        let lightBackgroundSuccess = Color(.sRGB, red: 211/255, green: 254/255, blue: 222/255, opacity: 1) 
        
        // Background Critical
        let lightBackgroundCritical = Color(.sRGB, red: 255/255, green: 240/255, blue: 240/255, opacity: 1) 
        
        // Background Warning
        let lightBackgroundWarning = Color(.sRGB, red: 255/255, green: 242/255, blue: 232/255, opacity: 1) 

        // Border
        
        // White
        let onDarkBorderWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        
        // Low Contrast
        let onDarkBorderLowContrast = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        
        // High Contrast
        let onDarkBorderHighContrast = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 

        // on DARK
        
        // Foreground White
        let onDarkForegroundWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        
        // Foreground 01
        let onDarkForeground01 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        
        // Foreground 02
        let onDarkForeground02 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        
        // Foreground 03
        let onDarkForeground03 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 

        // Border
        
        // Low Contrast
        let onLightBorderLowContrast = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        
        // Medium Contrast
        let onLightBorderMediumContrast = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        
        // High Contrast
        let onLightBorderHighContrast = Color(.sRGB, red: 192/255, green: 199/255, blue: 206/255, opacity: 1) 

        // on LIGHT
        
        // Foreground Black
        let onLightForegroundBlack = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 
        
        // Foreground 01
        let onLightForeground01 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 
        
        // Foreground 02
        let onLightForeground02 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 
        
        // Foreground 03
        let onLightForeground03 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        
        // Foreground 04
        let onLightForeground04 = Color(.sRGB, red: 159/255, green: 170/255, blue: 180/255, opacity: 1) 

        // Color

        // Semantic
        
        // Primary
        let semanticPrimary = Color(.sRGB, red: 69/255, green: 137/255, blue: 255/255, opacity: 1) 
        
        // Success
        let semanticSuccess = Color(.sRGB, red: 0/255, green: 164/255, blue: 84/255, opacity: 1) 
        
        // Critical
        let semanticCritical = Color(.sRGB, red: 210/255, green: 48/255, blue: 49/255, opacity: 1) 
        
        // Warning
        let semanticWarning = Color(.sRGB, red: 227/255, green: 107/255, blue: 0/255, opacity: 1) 

    }
}