import SwiftUI

// Generated by Supernova - do not modify manually
extension Text {
        
    // Docs
    // 11 Bold Caps
    func textStyleDocs11BoldCaps() -> some View {
        return self
            .font(Font.custom("RobotoBold", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 40 Bold
    func textStyleDocs40Bold() -> some View {
        return self
            .font(Font.custom("RobotoBlack", size: 40) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 32 Bold
    func textStyleDocs32Bold() -> some View {
        return self
            .font(Font.custom("RobotoBlack", size: 32) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 32 Bold Underline
    func textStyleDocs32BoldUnderline() -> some View {
        return self
            .font(Font.custom("RobotoBlack", size: 32) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 24 Bold
    func textStyleDocs24Bold() -> some View {
        return self
            .font(Font.custom("RobotoBlack", size: 24) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 24 Bold Underline
    func textStyleDocs24BoldUnderline() -> some View {
        return self
            .font(Font.custom("RobotoBlack", size: 24) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 20 Bold
    func textStyleDocs20Bold() -> some View {
        return self
            .font(Font.custom("RobotoBlack", size: 20) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 20 Bold Underline
    func textStyleDocs20BoldUnderline() -> some View {
        return self
            .font(Font.custom("RobotoBold", size: 20) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 16 Regular
    func textStyleDocs16Regular() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: 16) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 16 Regular Underline
    func textStyleDocs16RegularUnderline() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: 16) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 14 Regular
    func textStyleDocs14Regular() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: 14) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 14 Regular Underline
    func textStyleDocs14RegularUnderline() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: 14) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 14 Bold
    func textStyleDocs14Bold() -> some View {
        return self
            .font(Font.custom("RobotoBold", size: 14) 
            .underline() 
            .textCase(.uppercase) 
    }


    // Code
    // 12 Medium
    func textStyleCode12Medium() -> some View {
        return self
            .font(Font.custom("Fira MonoMedium", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 12 Regular
    func textStyleCode12Regular() -> some View {
        return self
            .font(Font.custom("Fira MonoRegular", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Medium
    func textStyleCode11Medium() -> some View {
        return self
            .font(Font.custom("Fira MonoMedium", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Medium Underline
    func textStyleCode11MediumUnderline() -> some View {
        return self
            .font(Font.custom("Fira MonoMedium", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Medium Italic
    func textStyleCode11MediumItalic() -> some View {
        return self
            .font(Font.custom("Fira MonoRegular Italic", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Bold
    func textStyleCode11Bold() -> some View {
        return self
            .font(Font.custom("Fira MonoBold", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }


    // Text
    // 11 Regular
    func textStyleText11Regular() -> some View {
        return self
            .font(Font.custom("PoppinsRegular", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Regular Italic
    func textStyleText11RegularItalic() -> some View {
        return self
            .font(Font.custom("PoppinsItalic", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Medium Underline
    func textStyleText11MediumUnderline() -> some View {
        return self
            .font(Font.custom("PoppinsMedium", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }


    // UI
    // 32 Regular
    func textStyleUi32Regular() -> some View {
        return self
            .font(Font.custom("PoppinsRegular", size: 32) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 32 Extrabold
    func textStyleUi32Extrabold() -> some View {
        return self
            .font(Font.custom("PoppinsExtraBold", size: 32) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 24 Extrabold
    func textStyleUi24Extrabold() -> some View {
        return self
            .font(Font.custom("PoppinsExtraBold", size: 24) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 14 Regular
    func textStyleUi14Regular() -> some View {
        return self
            .font(Font.custom("PoppinsRegular", size: 14) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 14 Semibold
    func textStyleUi14Semibold() -> some View {
        return self
            .font(Font.custom("PoppinsSemiBold", size: 14) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 12 Regular
    func textStyleUi12Regular() -> some View {
        return self
            .font(Font.custom("PoppinsRegular", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 12 Regular Underline
    func textStyleUi12RegularUnderline() -> some View {
        return self
            .font(Font.custom("PoppinsRegular", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 12 Regular Italic
    func textStyleUi12RegularItalic() -> some View {
        return self
            .font(Font.custom("PoppinsItalic", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 12 Medium
    func textStyleUi12Medium() -> some View {
        return self
            .font(Font.custom("PoppinsMedium", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 12 Semibold
    func textStyleUi12Semibold() -> some View {
        return self
            .font(Font.custom("PoppinsSemiBold", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 12 Semibold CAPS
    func textStyleUi12SemiboldCaps() -> some View {
        return self
            .font(Font.custom("PoppinsSemiBold", size: 12) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Regular
    func textStyleUi11Regular() -> some View {
        return self
            .font(Font.custom("PoppinsRegular", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Regular Caps
    func textStyleUi11RegularCaps() -> some View {
        return self
            .font(Font.custom("PoppinsRegular", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Semibold
    func textStyleUi11Semibold() -> some View {
        return self
            .font(Font.custom("PoppinsSemiBold", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Semibold CAPS
    func textStyleUi11SemiboldCaps() -> some View {
        return self
            .font(Font.custom("PoppinsSemiBold", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }

    // 11 Medium
    func textStyleUi11Medium() -> some View {
        return self
            .font(Font.custom("PoppinsMedium", size: 11) 
            .underline() 
            .textCase(.uppercase) 
    }


    // Typography

}